 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trainings", type: :request do
  
  # Training. As you add validations to Training, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Training.create! valid_attributes
      get trainings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      training = Training.create! valid_attributes
      get training_url(training)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_training_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      training = Training.create! valid_attributes
      get edit_training_url(training)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Training" do
        expect {
          post trainings_url, params: { training: valid_attributes }
        }.to change(Training, :count).by(1)
      end

      it "redirects to the created training" do
        post trainings_url, params: { training: valid_attributes }
        expect(response).to redirect_to(training_url(Training.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Training" do
        expect {
          post trainings_url, params: { training: invalid_attributes }
        }.to change(Training, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post trainings_url, params: { training: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested training" do
        training = Training.create! valid_attributes
        patch training_url(training), params: { training: new_attributes }
        training.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the training" do
        training = Training.create! valid_attributes
        patch training_url(training), params: { training: new_attributes }
        training.reload
        expect(response).to redirect_to(training_url(training))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        training = Training.create! valid_attributes
        patch training_url(training), params: { training: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested training" do
      training = Training.create! valid_attributes
      expect {
        delete training_url(training)
      }.to change(Training, :count).by(-1)
    end

    it "redirects to the trainings list" do
      training = Training.create! valid_attributes
      delete training_url(training)
      expect(response).to redirect_to(trainings_url)
    end
  end
end
